SQLALCHEMY_DATABASE_URI = 'mysql+mysqldb://{{MYSQL_USER}}:{{MYSQL_PASSWORD}}@{{MYSQL_HOST}}/{{MYSQL_DATABASE}}?charset={{MYSQL_CHARSET}}'
DEBUG = {{DEBUG}}
SECRET_KEY = '{{SECRET_KEY}}'
SERVER_NAME = '{{SERVER_NAME}}'

MAIL_ENABLE = {{MAIL_ENABLE}}
MAIL_SERVER = '{{MAIL_SERVER}}'
MAIL_PORT = {{MAIL_PORT}}
MAIL_USE_TLS = {{MAIL_TLS_ENABLE}}
MAIL_USE_SSL = {{MAIL_SSL_ENABLE}}
MAIL_USERNAME = '{{MAIL_USERNAME}}'
MAIL_PASSWORD = '{{MAIL_PASSWORD}}'
MAIL_DEFAULT_SENDER = '{{MAIL_SENDER}}'
ADMIN_MAIL = '{{ADMIN_MAIL}}'

BOOTSTRAP_SERVE_LOCAL = True

SQLALCHEMY_TRACK_MODIFICATIONS = False