#!/bin/bash
set -x
set -e
apk update
apk add python3 mariadb-client tzdata
apk add --virtual build-dependencies python3-dev build-base mariadb-dev
cd /srv/lugvpn-web
pip3 install -r requirements.txt
cd /
apk del --purge build-dependencies
rm -rf /var/cache/apk/*

